### PR TITLE
check if console CSS is supported

### PR DESCRIPTION
**Pull request by kounelios13**
if current browser is not chrome a warning will be outputed

### CODE REVIEW

**Comment by kostasx** [comment]
Actually, CSS works fine both on Safari and Firefox. Not sure about IE/Edge though. Maybe another type  of conditional to check if browser is IE/Edge?

**Comment by kounelios13** [comment]
I will check it
Στις 11 Μαΐ 2016 20:37, ο χρήστης "Kostas Minaidis" <
notifications@github.com> έγραψε:

**Comment by kounelios13** [comment]
added browser check

**Comment by kounelios13** [comment]
Are you sure it is working on firefox?

**Pull request closed without merging**
